name: Clean, Build Native Image

on:
  push:
    branches: graal_image
  pull_request:
    branches:
      - main

jobs:
  buildAndPush:
    runs-on: ubuntu-22.04
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Tag from version file
        run: |
          TAG=$(grep "tag=" config/version | cut -d'=' -f2)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Run build
        run: earthly +build --tag ${{ env.TAG }} --build_type=native-ci
