name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v4
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: 'Get Tag from version file
        run: |
          TAG=$(grep "tag=" version | cut -d'=' -f2)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Run build
        run: earthly --push +build-all-platforms --tag ${{ env.TAG }}
      - name: Docker Push
        run: docker push bloxbean/yaci-devkit:${{ env.TAG }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/yaci-devkit-${{env.VERSION}}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
