name: Clean, Build Native Image

on:
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [ "linux/amd64", "linux/arm64" ]
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v4
      - name: 'Get Tag from version file'
        run: |
          TAG=$(grep "tag=" config/version | cut -d'=' -f2)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Run build
        run: earthly +cli-native --tag ${{ env.TAG }}
