name: Clean, Build Native Image

on:
  push:
    branches: graal_image
  pull_request:
    branches:
      - main

jobs:
  buildAndPush:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Tag from version file
        run: |
          TAG=$(grep "tag=" config/version | cut -d'=' -f2)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Build native image
        run: ./gradlew --no-daemon -i -Pversion=${{ env.TAG }} clean build nativeCompile
        working-directory: ./applications/cli
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: yaci-cli-${{ matrix.platform }}
            path: ./applications/cli/build/native/nativeCompile/yaci-cli
