name: Build and Publish YaciDevKit Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tag name without prefix
        id: metadata
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Build and push
        env:
          TAG_NAME: ${{ steps.metadata.outputs.TAG_NAME }}
        uses: docker/build-push-action@v4
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bloxbean/yaci-devkit:latest,bloxbean/yaci-devkit:${{ env.TAG_NAME }}

