name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag name without prefix
        run: echo ::set-env name=TAG_NAME::${GITHUB_REF#refs/tags/v}
      - name: Print tag name
        run: echo $TAG_NAME
