name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref.replace('refs/tags/v', '') }}
    steps:
      - name: Print tag name
        run: echo $TAG_NAME
